### ISSUE TITLE
Getting unknown property: craft\models\UserGroup::uid

### ISSUE THREAD

**Issue by jpcarpenter** [superbigco/craft-usergroupfield#1]
Hitting this error when going to create an entry where the user group field is attached. The problematic code appears to be on line 146 of UserGroupFieldField.php. Stacktrace attached below.

[stacktrace.txt](https://github.com/superbigco/craft-usergroupfield/files/2901884/stacktrace.txt)

Craft version: 3.0.35
PHP: 7.0.32
Database driver & version: MySQL 5.7.23

**Comment by sjelfull** [comment]
I thought I had already required 3.1 in composer. It's basically because 3.1 started using uid's for everything, and I wanted to support that without adding extra code to check which versions we're using.

I'll constrain this Craft 3.1 and have release out soon.
