### ISSUE TITLE
Cannot uncheck user groups

### ISSUE THREAD

**Issue by chasegiunta** [superbigco/craft-usergroupfield#11]
After checking a user group and saving, unchecking and saving will unsuccessfully remove the user group.

**Comment by rocknrolaf** [comment]
Same issue here. Can be reproduced by checking only one checkbox in a group, save and trying to uncheck it (so no checkboxes are active).
It seems to be working if instead of "checkboxSelect" a "checkboxGroupField" is used within src/templates/_components/fields/UserGroupFieldField_input.twig

**Comment by tomdavies** [comment]
@chasegiunta @rocknrolaf hit this too, easy fix in #12

**Comment by sjelfull** [comment]
Tagged 1.0.3 with #12 that should fix this.

**Comment by andrewfairlie** [comment]
🙇‍♂️ Thank you :)
