### ISSUE TITLE
User groups do not remain selected when editing (intermittent)

### ISSUE THREAD

**Issue by iamkeir** [superbigco/craft-usergroupfield#15]
### Describe the bug
When creating an entry, then editing the entry and changing the user group field, sometimes it loses all user group settings. Been trying to get a reliable replication but it seems a bit random.

### To reproduce
1. Create an entry and select user group/s
2. Edit entry and change user group/s
3. View entry, notice user groups are all unticked

### Expected behaviour
It should maintain the selected user groups.

### Screenshots
https://jmp.sh/twrI8rK

### Versions
- Plugin version: 1.0.3
- Craft version: Craft Pro 3.7.10

**Comment by xo-dev** [comment]
Same problem here. On every save the user group fields gets empty and the permissions are unset. Will there be a fix in the near future or do we have to find an other solution for group permissions?

**Comment by iamkeir** [comment]
@xo-dev Fingers crossed it can be fixed but we need to be patient with open source/free plugins. I wish I had better PHP to try and fix myself.

**Comment by engram-design** [comment]
Should've been fixed in [1.0.4](https://github.com/verbb/user-group-field/releases/tag/1.0.4)
