### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by idawgik** [superbigco/craft-usergroupfield#18]
Hello, I wanted to check in on support for Craft 4. 

I have a fairly major project that is using this plugin as a critical piece of functionality, so it's a roadblock to updating. Just wanted to know if there's an expected timeframe for support so I can keep the client updated and set expectations appropriately.

Thank you.

**Comment by sjelfull** [comment]
Hi! Yeah, I have plans to support Craft 4, but it is tricky with finding the time now that I have a boxfresh kid. Happy to take a PR or get paid to upgrade it if it is essential in your project(s) in the mean time.

**Comment by engram-design** [comment]
We've recently acquired this plugin from the Superbig team. Read our [blog post](https://verbb.io/blog/some-plugins-from-superbig) for more details.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/user-group-field/releases/tag/3.0.0)
