### ISSUE TITLE
Migration From 2 -> 3

### ISSUE THREAD

**Issue by theskyfloor** [superbigco/craft-usergroupfield#2]
Hey Fred,

What are the chances you could write a migration for this field from Craft 2:

https://github.com/quebecstudio/usergroupfield

To upgrade to this plug-in? Thanks for the consideration.

**Comment by sjelfull** [comment]
Sounds like a good idea, but I don't have much room to do this anytime soon, so much more likely to happen if someone submits a PR for it.

**Comment by engram-design** [comment]
Added in [2.0.1](https://github.com/verbb/user-group-field/releases/tag/2.0.1)
