### ISSUE TITLE
Allow Craft::$app->getUserGroups()->getAllGroups(); to be cached.

### ISSUE THREAD

**Issue by anchovy** [superbigco/craft-usergroupfield#21]
### What are you trying to do?

We've got a site with a lot of pages and lots of different user groups. Some pages need to be restricted to one or more groups - others are open to all.

![image](https://github.com/verbb/user-group-field/assets/599005/3aa6155f-58f5-4683-a233-99525e2abc22)

When building the nav for each page we've got to check if there are any restrictions - this seems to be calling the following query every single time for each page:
```
SELECT `id`, `name`, `handle`, `description`, `uid`
FROM `usergroups`
ORDER BY `name`
```

In the debug tool bar we're seeing this called 270+ times.

### What's your proposed solution?

Add the possibility to cache this query for the session - possibly passing in a flag i.e. `$entry->restrictedAccess->getGroups($cache=true);`

Thought a flag was better than a env var etc - as it I don't think it should be cached when in the CP or fired from custom modules/plugins where potentially new user groups could be added/removed etc.

I've got this working locally - reduces the 270+ db queries down to 1 on first-page load and then 0 on subsequent loads within the same session; can do a PR if you like?

**Comment by engram-design** [comment]
Sounds good, and would love to see a PR even just to get things started!

**Comment by anchovy** [comment]
Sweet - done! Happy to make changes and feel free to rip it apart!

**Comment by engram-design** [comment]
Added in [3.0.2](https://github.com/verbb/user-group-field/releases/tag/3.0.2)
