### ISSUE TITLE
Entry queries

### ISSUE THREAD

**Issue by fthues** [superbigco/craft-usergroupfield#3]
I've created a field called `userGroup` for all my `pages` entries, type 'dropdown'. I'm trying to query entries based on their `userGroup` value like you would for other field types like this:

```
craft.entries().section('pages').userGroup(3).one()
```

I don't get any results unfortunately. I've also tried using the group's handle instead of the ID and querying with an array instead of a single value, but it won't return the result I'm expecting. 

I'm guessing this is down to how the field's values are serialized?

**Comment by sjelfull** [comment]
Yeah, probably is. I would have to look into this to see what I can do.

**Comment by billymedia** [comment]
I also need the ability to query all assets based on the users usergroup, did you make any progress with this at all?

**Comment by engram-design** [comment]
Added in [2.0.1](https://github.com/verbb/user-group-field/releases/tag/2.0.1). Note you'll need to query on the user group `uid` as the `id` isn't reliable enough, due to them being stored in Project Config. When applied can often have different IDs from one environment to the other.

```twig
{% set userGroup = craft.app.userGroups.getGroupByHandle('myUserGroup') %}

{% set entries = craft.entries.section('blog').userGroupField(userGroup.uid).all() %}
```
