### ISSUE TITLE
Values on checkbox option not copied to other languages

### ISSUE THREAD

**Issue by jurriaanr** [superbigco/craft-usergroupfield#5]
If you have multiple languages and set the field to not translatable, if you save the entry the values will not be saved for the other language. Even worse if you use the checkbox option it will clear the values of the field for the other language.

Craft edition & version | Craft Pro 3.3.3
User Group Field | 1.0.2

**Comment by outline4** [comment]
will this be fixed anytime soon?

**Comment by outline4** [comment]
Damn, I just realized that this plugin is absolutely not usable this way... 
Is there a hotfix or a workaround?

**Comment by outline4** [comment]
Ok, so I've found a workaround which does not involve this plugin and it works like a charm: 

I've created a checkboxes field called "cf_userRights_checkboxes" with the label as "user-group name" and the value is "user-group id".

To check if a user has permissions: 

	{% set condition = 0 %}
	{% for userGroup in currentUser.getGroups %}
		{% if userGroup.id in entry.cf_userRights_checkboxes %}
			{% set condition = 1 %}
		{% endif %}
	{% endfor %}
	
	{% if condition == 1 %}
		please enter
	{% else %}
		sorry, not you
	{% endif %}

Of course it won't add user-groups dynamically, but it's enough for me to ditch this plugin. 
It would have been a great plugin, but I'm all for less plugins. 

Thanks for all the fish.  
Stefan

**Comment by enobis-dev** [comment]
Is there any traction on this?  This is a major problem, plugin cannot be used with multi-site set up as is...

**Comment by sjelfull** [comment]
@enobis-dev I haven't had a chance to look into it yet.

**Comment by enobis-dev** [comment]
Ugh, this is so unfortunate, the plugin is conceptually exactly what seems to be missing as a standard in Craft, it's great you implemented it, but this plugin has some of these minor bugs that makes it unusable in a production environment at the moment - if you could look into this and the other, then the plugin would be perfect.

**Comment by enobis-dev** [comment]
As a follow up, we had to stop using this plugin, just way too many little issues, along with the one in this thread.  I think conceptually you have a great idea here as it is something missing from the core functionality, but we ended up having to make our own workaround similar to what @outline4 suggested.

**Comment by sjelfull** [comment]
I understand. Sadly its low on the list of things I have to prioritize at the moment, but I will get to it eventually.

**Comment by engram-design** [comment]
I can't replicate this sorry, it's working pretty flawlessly when dealing with translatable content. I've tested with brand new elements, and existing elements and adding the new fields to it. All work as you expect. No difference in the display type used.

Feel free to respond if you're still seeing this issue.
