### ISSUE TITLE
No Group Selected

### ISSUE THREAD

**Issue by enobis-dev** [superbigco/craft-usergroupfield#7]
I brought this up in a chat session a while back, but see no movement on this plugin regarding this request or the other bugs posted.

When there are user groups selected for an entry and the entry is saved, then when you go back into the entry, you cannot deselect so that there are no groups selected.  If you save with no groups selected and come back to the entry, at least one of the selected groups is still selected.

Essentially, there is no way to remove all the selected groups from a saved entry.

**Comment by sjelfull** [comment]
Tagged 1.0.3 with #12 that should fix this.
